version: "3"
services: 
  web:
    build: 
      context: ./client
      dockerfile: ./Dockerfile
    ports: 
      - 80:80
  web-api:
    build: 
      context: ./server
      dockerfile: ./Dockerfile
    ports: 
      - 1337:1337    